/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface AppAddArticle {}
  interface AppAddArticleAttributes extends StencilHTMLAttributes {}

  interface AppDelete {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface AppDeleteAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface AppEdit {
    'match': MatchResults;
  }
  interface AppEditAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppFetchId {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface AppFetchIdAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface AppFetch {
    'load': () => void;
    'name': string;
  }
  interface AppFetchAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface AppFooter {}
  interface AppFooterAttributes extends StencilHTMLAttributes {}

  interface AppHeader {}
  interface AppHeaderAttributes extends StencilHTMLAttributes {}

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppAddArticle': Components.AppAddArticle;
    'AppDelete': Components.AppDelete;
    'AppEdit': Components.AppEdit;
    'AppFetchId': Components.AppFetchId;
    'AppFetch': Components.AppFetch;
    'AppFooter': Components.AppFooter;
    'AppHeader': Components.AppHeader;
    'AppHome': Components.AppHome;
    'AppRoot': Components.AppRoot;
  }

  interface StencilIntrinsicElements {
    'app-add-article': Components.AppAddArticleAttributes;
    'app-delete': Components.AppDeleteAttributes;
    'app-edit': Components.AppEditAttributes;
    'app-fetch-id': Components.AppFetchIdAttributes;
    'app-fetch': Components.AppFetchAttributes;
    'app-footer': Components.AppFooterAttributes;
    'app-header': Components.AppHeaderAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-root': Components.AppRootAttributes;
  }


  interface HTMLAppAddArticleElement extends Components.AppAddArticle, HTMLStencilElement {}
  var HTMLAppAddArticleElement: {
    prototype: HTMLAppAddArticleElement;
    new (): HTMLAppAddArticleElement;
  };

  interface HTMLAppDeleteElement extends Components.AppDelete, HTMLStencilElement {}
  var HTMLAppDeleteElement: {
    prototype: HTMLAppDeleteElement;
    new (): HTMLAppDeleteElement;
  };

  interface HTMLAppEditElement extends Components.AppEdit, HTMLStencilElement {}
  var HTMLAppEditElement: {
    prototype: HTMLAppEditElement;
    new (): HTMLAppEditElement;
  };

  interface HTMLAppFetchIdElement extends Components.AppFetchId, HTMLStencilElement {}
  var HTMLAppFetchIdElement: {
    prototype: HTMLAppFetchIdElement;
    new (): HTMLAppFetchIdElement;
  };

  interface HTMLAppFetchElement extends Components.AppFetch, HTMLStencilElement {}
  var HTMLAppFetchElement: {
    prototype: HTMLAppFetchElement;
    new (): HTMLAppFetchElement;
  };

  interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {}
  var HTMLAppFooterElement: {
    prototype: HTMLAppFooterElement;
    new (): HTMLAppFooterElement;
  };

  interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {}
  var HTMLAppHeaderElement: {
    prototype: HTMLAppHeaderElement;
    new (): HTMLAppHeaderElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLElementTagNameMap {
    'app-add-article': HTMLAppAddArticleElement
    'app-delete': HTMLAppDeleteElement
    'app-edit': HTMLAppEditElement
    'app-fetch-id': HTMLAppFetchIdElement
    'app-fetch': HTMLAppFetchElement
    'app-footer': HTMLAppFooterElement
    'app-header': HTMLAppHeaderElement
    'app-home': HTMLAppHomeElement
    'app-root': HTMLAppRootElement
  }

  interface ElementTagNameMap {
    'app-add-article': HTMLAppAddArticleElement;
    'app-delete': HTMLAppDeleteElement;
    'app-edit': HTMLAppEditElement;
    'app-fetch-id': HTMLAppFetchIdElement;
    'app-fetch': HTMLAppFetchElement;
    'app-footer': HTMLAppFooterElement;
    'app-header': HTMLAppHeaderElement;
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
